//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_ID { get; set; }
        public int Service_ID { get; set; }
        public string Order_Status { get; set; }
        public string Service_Status { get; set; }
        public string Lead_Time { get; set; }
    
        public virtual Services Services { get; set; }
    }
}
