//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Bloods = new HashSet<Bloods>();
        }
    
        public int Patient_ID { get; set; }
        public string Full_Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string GUI { get; set; }
        public string Email { get; set; }
        public int Social_Sec_Number { get; set; }
        public string EIN { get; set; }
        public string Social_Type { get; set; }
        public string Phone { get; set; }
        public int Password_S { get; set; }
        public int Password_N { get; set; }
        public string Date_Of_Birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bloods> Bloods { get; set; }
    }
}
